<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Assetmanager\Module'                        => __DIR__ . '/Module.php',
    'Assetmanager\Controller\IndexController' => __DIR__ . '/src/Assetmanager/Controller/IndexController.php',
    'AssetmanagerTest\Framework\TestCase'        => __DIR__ . '/tests/Assetmanager/Framework/TestCase.php',
    'AssetmanagerTest\SampleTest'                => __DIR__ . '/tests/Assetmanager/SampleTest.php',
);
